# This is the file to set up the PostgreSQL database locally
# Refer to README file for command to spin up the database.


version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: kestra_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      POSTGRES_DB: kestra
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
